#!/usr/bin/env python3

import os
from pathlib import Path
import shutil

for (root,dirnames,filenames) in os.walk("files/"):
    for filename in filenames:
        fullpath = Path(os.path.join(root,filename))
        src = fullpath
        dst = '/' / fullpath.relative_to(fullpath.parts[0])
        try:
            if src.stat().st_mtime <= dst.stat().st_mtime:
                continue
        except:
            pass
        try:
            try:
                os.unlink(dst)
            except:
                pass
            print(f"* installed: {dst}")
            shutil.copy2(src,dst,follow_symlinks=False)
        except:
            print('FAILED')
            pass
