#!/bin/sh

apt update -y
apt install -y \
    sshfs \
    tmux \
    emacs-gtk \
    ffmpeg \
    htop \
    btop \
    python3 \
    curl \
    build-essential \
    clangd \
    v4l-utils \
    vlc

flatpak install \
        app.zen_browser.zen \
        net.werwolv.ImHex
