#!/usr/bin/env python3

import os
from pathlib import Path
import shutil

for (root,dirnames,filenames) in os.walk("files/"):
    for filename in filenames:
        fullpath = Path(os.path.join(root,filename))
        src = fullpath
        dst = '/' / fullpath.relative_to(fullpath.parts[0])
        try:
            if src.stat().st_mtime <= dst.stat().st_mtime:
                print(f"* {src}: not newer")
                continue
        except:
            pass
        print(f"* {src} -> {dst}")
        try:
            os.unlink(dst)
            shutil.copyfile(src,dst,follow_symlinks=False)
        except:
            print('FAILED')
            pass
