#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

install_flatpak_and_flathub() {
    if ! command -v flatpak >/dev/null 2>&1; then
        if command -v apt >/dev/null 2>&1; then
            apt install -y flatpak
        elif command -v pacman >/dev/null 2>&1; then
            pacman -S flatpak flatpak-kcm --noconfirm
        fi
    fi

    if ! flatpak remotes | grep -q "^flathub"; then
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    fi
}

if command -v apt >/dev/null 2>&1; then
    apt update -y
    apt install -y \
        sshfs \
        tmux \
        emacs-gtk \
        ffmpeg \
        htop \
        btop \
        python3 \
        curl \
        build-essential \
        clangd \
        v4l-utils \
        vlc

    install_flatpak_and_flathub
    flatpak install -y \
        app.zen_browser.zen \
        net.werwolv.ImHex
elif command -v pacman >/dev/null 2>&1; then
    pacman -Syu --noconfirm
    pacman -S \
           base-devel \
           btop \
           clang \
           curl \
           emacs-wayland \
           ffmpeg \
           htop \
           python3 \
           solaar \
           sshfs \
           tmux \
           v4l-utils \
           vlc \
           zen-browser-bin \
           --noconfirm

    install_flatpak_and_flathub
    flatpak install -y \
            com.github.tchx84.Flatseal \
            io.github.ungoogled_software.ungoogled_chromium \
            me.proton.Mail \
            net.werwolv.ImHex \
            org.ghidra_sre.Ghidra \
            org.libretro.RetroArch \
            org.signal.Signal \
            hu.irl.cameraactrls \
            com.chatterino.chatterino
else
    echo "Error: No supported package manager found (apt or pacman)" >&2
    exit 1
fi
