#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

if command -v apt >/dev/null 2>&1; then
    apt update -y
    apt install -y \
        sshfs \
        tmux \
        emacs-nox \
        ffmpeg \
        htop \
        btop \
        python3 \
        curl
elif command -v pacman >/dev/null 2>&1; then
    pacman -Syu --noconfirm
    pacman -S \
           sshfs \
           tmux \
           emacs-nox \
           ffmpeg \
           htop \
           btop \
           python3 \
           curl \
           --noconfirm
else
    echo "Error: No supported package manager found (apt or pacman)" >&2
    exit 1
fi
