#!/usr/bin/env python3

import os
from pathlib import Path
import shutil

for (root,dirnames,filenames) in os.walk("files/"):
    for filename in filenames:
        try:
            fullpath = Path(os.path.join(root,filename))
            src = '/' / fullpath.relative_to(fullpath.parts[0])
            dst = fullpath
            if src.stat().st_mtime <= dst.stat().st_mtime:
                continue
            print(f"* updated: {dst}")
            shutil.copy2(src,dst,follow_symlinks=False)
        except Exception as e:
            print(f"* exception: {e}")
