[ids]

*
0002:000a

[main]

capslock = leftcontrol
middlemouse = layer(nav)

[nav]

a = home
w = leftmeta
e = end
d = delete
f = back
g = forward
p = pageup
n = pagedown
b = backspace
h = left
k = up
j = down
l = right
